Refactor coroutine traits, Using concept
alibaba/async_simple pull request #206
Opened 2022-11-08 09:08 UTC by 4kangjc

## Why

## What is changing

## Example

2022-11-08 09:15 UTC, ChuanqiXu9 approved these changes
LGTM. Thanks.

2022-11-08 09:39 UTC, 4kangjc commented
看上去是`benchmarks/PureSwitch.bench.cpp` 的 `Generator`这里的问题

2022-11-08 10:28 UTC, 4kangjc commented
好奇怪啊，看起来是`FutrueAwaiter`没有生效？

2022-11-08 10:48 UTC, 4kangjc commented
> 好奇怪啊，看起来是`FutrueAwaiter`没有生效？
> 

为什么不直接把awaiter写到future里呢

2022-11-08 11:56 UTC, 4kangjc commented
> > 好奇怪啊，看起来是`FutrueAwaiter`没有生效？
> 
> 为什么不直接把awaiter写到future里呢

https://github.com/alibaba/async_simple/blob/07e322f450bbb2262ffe9e8cec1988da3b4eb799/async_simple/coro/FutureAwaiter.h#L46
`lvalue`也被move吗

2022-11-08 12:18 UTC, RainMark commented
> > > 好奇怪啊，看起来是`FutrueAwaiter`没有生效？
> > 
> > 
> > 为什么不直接把awaiter写到future里呢
> 
> https://github.com/alibaba/async_simple/blob/07e322f450bbb2262ffe9e8cec1988da3b4eb799/async_simple/coro/FutureAwaiter.h#L46
> 
> 
> `lvalue`也被move吗

这里只希望接受future的右值，这样或许更合适?

```c++
template <typename T>
auto operator co_await(Future<T>&& future) {
    return coro::FutureAwaiter(future);
}
```

2022-11-08 12:53 UTC, 4kangjc commented
> > > > 好奇怪啊，看起来是`FutrueAwaiter`没有生效？
> > > 
> > > 
> > > 为什么不直接把awaiter写到future里呢
> > 
> > 
> > https://github.com/alibaba/async_simple/blob/07e322f450bbb2262ffe9e8cec1988da3b4eb799/async_simple/coro/FutureAwaiter.h#L46
> > 
> > `lvalue`也被move吗
> 
> 这里只希望接受future的右值，这样或许更合适?
> 
> ```c++
> template <typename T>
> auto operator co_await(Future<T>&& future) {
>     return coro::FutureAwaiter(future);
> }
> ```

我觉得可以

2022-11-08 14:44 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
```suggestion
    operator co_await(std::move(awaitable));
```

`T&&` 不一定是右值

2022-11-09 01:35 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> `T&&` 不一定是右值

T&&不一定是右值，所以用的`std::forward`啊

2022-11-09 02:02 UTC, 4kangjc commented
`clang`还要加个构造函数

2022-11-09 02:08 UTC, 4kangjc commented
`HasGlobalCoAwaitOperator`在windows上还是有点问题

2022-11-09 02:21 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > `T&&` 不一定是右值
> 
> T&&不一定是右值，所以用的`std::forward`啊

意思是这里 co_await 的参数类型需要是右值，`std::forward<T>` 后，得到的结果不一定是右值。

2022-11-09 05:00 UTC, RainMark commented on async_simple/coro/FutureAwaiter.h
> +auto operator co_await(Future<T> future) noexcept
这样会触发 future copy吧

2022-11-09 05:12 UTC, 4kangjc commented on async_simple/coro/FutureAwaiter.h
> +auto operator co_await(Future<T> future) noexcept
`Future`不是禁止了copy吗，只会move的

2022-11-09 05:15 UTC, RainMark commented on async_simple/coro/FutureAwaiter.h
> +auto operator co_await(Future<T> future) noexcept
哦哦，那就没问题了

2022-11-09 06:59 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > `T&&` 不一定是右值
> > 
> > 
> > T&&不一定是右值，所以用的`std::forward`啊
> 
> 意思是这里 co_await 的参数类型需要是右值，`std::forward<T>` 后，得到的结果不一定是右值。
好像不太行

2022-11-09 07:03 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > `T&&` 不一定是右值
> > > 
> > > 
> > > T&&不一定是右值，所以用的`std::forward`啊
> > 
> > 
> > 意思是这里 co_await 的参数类型需要是右值，`std::forward<T>` 后，得到的结果不一定是右值。
> 
> 好像不太行

改成`operator co_await(std::declval<T>())`也不行

2022-11-09 07:10 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > > `T&&` 不一定是右值
> > > > 
> > > > 
> > > > T&&不一定是右值，所以用的`std::forward`啊
> > > 
> > > 
> > > 意思是这里 co_await 的参数类型需要是右值，`std::forward<T>` 后，得到的结果不一定是右值。
> > 
> > 
> > 好像不太行
> 
> 改成`operator co_await(std::declval<T>())`也不行

奇怪的是我用vs2022智能补全，提示什么的都没问题，编译倒是报错

2022-11-09 07:12 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +concept HasGlobalCoAwaitOperator = HasGlobalCoAwaitOperatorHelp<T>::value;
这里加个 FIXME 吧，说明原来的写法不行，但原因但不清楚

2022-11-09 07:12 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
也有可能是 MSVC 的编译器有问题，concept 比较新，有bug也很正常

2022-11-09 07:20 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +concept HasGlobalCoAwaitOperator = HasGlobalCoAwaitOperatorHelp<T>::value;
行

2022-11-09 07:30 UTC, RainMark approved these changes

2022-11-09 07:34 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> 也有可能是 MSVC 的编译器有问题，concept 比较新，有bug也很正常

![20156fcea6b05a040d971b21051dace](https://user-images.githubusercontent.com/73515066/200767030-bbdce416-60e6-4933-9b2b-377b28064da0.png)

2022-11-09 07:43 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> 
给微软提个issues？

2022-11-09 08:59 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
我觉得可以；另外这里如果把 `operator co_await` 的定义放到 concept 上面应该能编过。

2022-11-09 09:17 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > 给微软提个issues？
> 
> [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)

hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。

2022-11-09 09:17 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +concept HasGlobalCoAwaitOperator = HasGlobalCoAwaitOperatorHelp<T>::value;
把这个改了应该就能合了

2022-11-09 09:24 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > 给微软提个issues？
> > 
> > 
> > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> 
> hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。

呃呃也是

2022-11-09 09:45 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> 我觉得可以；另外这里如果把 `operator co_await` 的定义放到 concept 上面应该能编过。
```cpp
template <class T, class = std::void_t<decltype(operator co_await(std::declval<T>()))>>
concept HasGlobalCoAwaitOperator = true;
```
这样吗？
```
error: could not convert 'std::declval<async_simple::coro::B&>()' from 'async_simple::coro::B' to 'async_simple::coro::A'
   45 |     T, std::void_t<decltype(operator co_await(std::declval<T>()))>>
```

2022-11-09 09:46 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > 给微软提个issues？
> > 
> > 
> > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> 
> hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。

我先关了，等等再看看怎么给编译器提

2022-11-09 09:51 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > 我觉得可以；另外这里如果把 `operator co_await` 的定义放到 concept 上面应该能编过。
> 
> ```c++
> template <class T, class = std::void_t<decltype(operator co_await(std::declval<T>()))>>
> concept HasGlobalCoAwaitOperator = true;
> ```
> 
> 这样吗？
> 
> ```
> error: could not convert 'std::declval<async_simple::coro::B&>()' from 'async_simple::coro::B' to 'async_simple::coro::A'
>    45 |     T, std::void_t<decltype(operator co_await(std::declval<T>()))>>
> ```

我的意思是

```
struct A {};
auto operator co_await(A) {...}

template<class T>
concept has_global_xxxx = ...
```

2022-11-09 09:52 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > 给微软提个issues？
> > > 
> > > 
> > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > 
> > 
> > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> 
> 我先关了，等等再看看怎么给编译器提

在 MSVC 社区

2022-11-09 09:55 UTC, frederick-vs-ja commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > 给微软提个issues？
> > > 
> > > 
> > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > 
> > 
> > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> 
> 我先关了，等等再看看怎么给编译器提

应该是 [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851) 这个 bug ，已经有人提过了。
看起来 MSVC 在 requires 子句里面遇到无限定的函数调用（包括运算符函数）且参数类型为待决时都没有默认进行 ADL ，只在前面通常查找找到函数声明时才进行 ADL 。

```C++
struct deleting_workaround_for_msvc {};
void operator co_await(deleting_workaround_for_msvc) = delete;
```
我想可以写这个 workaround 。

2022-11-09 10:14 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > > 给微软提个issues？
> > > > 
> > > > 
> > > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > > 
> > > 
> > > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> > 
> > 
> > 我先关了，等等再看看怎么给编译器提
> 
> 应该是 [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851) 这个 bug ，已经有人提过了。 看起来 MSVC 在 requires 子句里面遇到无限定的函数调用（包括运算符函数）且参数类型为待决时都没有默认进行 ADL ，只在前面通常查找找到函数声明时才进行 ADL 。
> 
> ```c++
> struct deleting_workaround_for_msvc {};
> void operator co_await(deleting_workaround_for_msvc) = delete;
> ```
> 
> 我想可以写这个 workaround 。
为什么在类里重载`co_await`不会有这个bug呢

2022-11-09 10:15 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > > > 给微软提个issues？
> > > > > 
> > > > > 
> > > > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > > > 
> > > > 
> > > > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> > > 
> > > 
> > > 我先关了，等等再看看怎么给编译器提
> > 
> > 
> > 应该是 [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851) 这个 bug ，已经有人提过了。 看起来 MSVC 在 requires 子句里面遇到无限定的函数调用（包括运算符函数）且参数类型为待决时都没有默认进行 ADL ，只在前面通常查找找到函数声明时才进行 ADL 。
> > ```c++
> > struct deleting_workaround_for_msvc {};
> > void operator co_await(deleting_workaround_for_msvc) = delete;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我想可以写这个 workaround 。
> 
> 为什么在类里重载`co_await`不会有这个bug呢

将全局的`co_await`提前可以解决，但不可能确保全局的`co_await`都在前面

2022-11-09 10:16 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > > 给微软提个issues？
> > > > 
> > > > 
> > > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > > 
> > > 
> > > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> > 
> > 
> > 我先关了，等等再看看怎么给编译器提
> 
> 应该是 [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851) 这个 bug ，已经有人提过了。 看起来 MSVC 在 requires 子句里面遇到无限定的函数调用（包括运算符函数）且参数类型为待决时都没有默认进行 ADL ，只在前面通常查找找到函数声明时才进行 ADL 。
> 
> ```c++
> struct deleting_workaround_for_msvc {};
> void operator co_await(deleting_workaround_for_msvc) = delete;
> ```
> 
> 我想可以写这个 workaround 。

```cpp
struct deleting_workaround_for_msvc {};
void operator co_await(deleting_workaround_for_msvc) = delete;
```
好像不行？只有把`co_await A`提前才没问题

2022-11-09 10:37 UTC, frederick-vs-ja commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > > > 给微软提个issues？
> > > > > 
> > > > > 
> > > > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > > > 
> > > > 
> > > > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> > > 
> > > 
> > > 我先关了，等等再看看怎么给编译器提
> > 
> > 
> > 应该是 [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851) 这个 bug ，已经有人提过了。 看起来 MSVC 在 requires 子句里面遇到无限定的函数调用（包括运算符函数）且参数类型为待决时都没有默认进行 ADL ，只在前面通常查找找到函数声明时才进行 ADL 。
> > ```c++
> > struct deleting_workaround_for_msvc {};
> > void operator co_await(deleting_workaround_for_msvc) = delete;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我想可以写这个 workaround 。
> 
> ```c++
> struct deleting_workaround_for_msvc {};
> void operator co_await(deleting_workaround_for_msvc) = delete;
> ```
> 
> 好像不行？只有把`co_await A`提前才没问题


写到 `concept` 前面应该就可以，不过还有一些奇怪的问题（[Godbolt link](https://godbolt.org/z/9r6fedh7n)）。

2022-11-09 10:46 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +    operator co_await(std::forward<T>(awaitable));
> > > > > > > 给微软提个issues？
> > > > > > 
> > > > > > 
> > > > > > [microsoft/STL#3198](https://github.com/microsoft/STL/issues/3198)
> > > > > 
> > > > > 
> > > > > hmmm 这个大概率是 MSVC 编译器的 bug 而不是 MSSTL 的。
> > > > 
> > > > 
> > > > 我先关了，等等再看看怎么给编译器提
> > > 
> > > 
> > > 应该是 [DevCom-10160851](https://developercommunity.visualstudio.com/t/10160851) 这个 bug ，已经有人提过了。 看起来 MSVC 在 requires 子句里面遇到无限定的函数调用（包括运算符函数）且参数类型为待决时都没有默认进行 ADL ，只在前面通常查找找到函数声明时才进行 ADL 。
> > > ```c++
> > > struct deleting_workaround_for_msvc {};
> > > void operator co_await(deleting_workaround_for_msvc) = delete;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我想可以写这个 workaround 。
> > 
> > 
> > ```c++
> > struct deleting_workaround_for_msvc {};
> > void operator co_await(deleting_workaround_for_msvc) = delete;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 好像不行？只有把`co_await A`提前才没问题
> 
> 写到 `concept` 前面应该就可以，不过还有一些奇怪的问题（[Godbolt link](https://godbolt.org/z/9r6fedh7n)）。

我们只能确保库里定义的`co_await`写在前面，用户要自定义就麻烦了

2022-11-09 12:40 UTC, ChuanqiXu9 commented on async_simple/coro/Traits.h
> +// FIXME: MSVC compiler bug
FIXME 写清楚一些吧，可以贴一下链接

2022-11-09 12:46 UTC, 4kangjc commented on async_simple/coro/Traits.h
> +// FIXME: MSVC compiler bug
> FIXME 写清楚一些吧，可以贴一下链接

贴这个链接吗 https://developercommunity.visualstudio.com/t/10160851

2022-11-09 15:29 UTC, ChuanqiXu9 commented
奇怪了 coro_test 的 collectAllBatch 会报错，我先注册个 Issue 再 rerun 一下

2022-11-09 15:38 UTC, ChuanqiXu9 requested changes

2022-11-09 15:38 UTC, ChuanqiXu9 commented on async_simple/coro/test/FutureAwaiterTest.cpp
> +        auto val = co_await std::move(fut);
这个地方也应该回退，改变行为了。

2022-11-09 16:29 UTC, 4kangjc commented on async_simple/coro/FutureAwaiter.h
> +static_assert(!HasGlobalCoAwaitOperator<Future<int>&>);
好

2022-11-09 16:41 UTC, 4kangjc commented on async_simple/coro/FutureAwaiter.h
> +auto operator co_await(Future<T> future) noexcept
这里加上右值引用应该能少一次move，这里主要参考https://en.cppreference.com/w/cpp/coroutine/coroutine_traits里awaiter的实现

2022-11-09 16:41 UTC, 4kangjc commented on async_simple/coro/FutureAwaiter.h
> +auto operator co_await(Future<T> future) noexcept
明天我回退一下

2022-11-10 02:15 UTC, ChuanqiXu9 commented on async_simple/coro/test/FutureAwaiterTest.cpp
> +        auto val = co_await std::move(fut);
> 考虑到operator co_await对左值的future也进行了move，万一用户在await后继续使用了future怎么办呢

像 co_await Lazy 之后 Lazy 不能再使用一样，这个算 co_await 的语义吧。

2022-11-10 03:01 UTC, 4kangjc commented on async_simple/coro/test/FutureAwaiterTest.cpp
> +        auto val = co_await std::move(fut);
> > 考虑到operator co_await对左值的future也进行了move，万一用户在await后继续使用了future怎么办呢
> 
> 像 co_await Lazy 之后 Lazy 不能再使用一样，这个算 co_await 的语义吧。

OK

2022-11-10 05:56 UTC, ChuanqiXu9 approved these changes
LGTM.

2022-11-10 05:56 UTC, merged

2022-11-10 08:02 UTC, RainMark commented on async_simple/coro/FutureAwaiter.h
> +auto operator co_await(Future<T> future) noexcept
> 这里加上右值引用应该能少一次move，这里主要参考[https://en.cppreference.com/w/cpp/coroutine/coroutine_traits里awaiter的实现](https://en.cppreference.com/w/cpp/coroutine/coroutine_traits%E9%87%8Cawaiter%E7%9A%84%E5%AE%9E%E7%8E%B0)

我一开始评论的就想这样，不过这样确实导致会写 co_await std::move(fut)，比较难看