feat: add the interface of `coro::ConditionVarable` notifyOne and notifyAll
alibaba/async_simple pull request #266
Opened 2022-12-19 03:56 UTC by 4kangjc

## Why

## What is changing

## Example

2022-12-19 05:41 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    ConditionVariableAwaiter<Lock>* _waiters = nullptr;
这两个不能复用吗

2022-12-19 05:41 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    void notifyAll() noexcept;
```suggestion
    void notify() noexcept { return notifyAll(); }
    void notifyOne() noexcept;
    void notifyAll() noexcept;
```

2022-12-19 05:41 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    void notifyAll() noexcept;
这样可以避免两次同样的实现

2022-12-19 05:57 UTC, 4kangjc commented on async_simple/coro/ConditionVariable.h
> +    ConditionVariableAwaiter<Lock>* _waiters = nullptr;
> 这两个不能复用吗

hmmm, `Mutex`的`_state`和`_awaiters`稍稍有点不同

2022-12-19 06:02 UTC, 4kangjc commented on async_simple/coro/ConditionVariable.h
> +    ConditionVariableAwaiter<Lock>* _waiters = nullptr;
噢，你说的是`_awaiters`和`_waiters`吗

2022-12-19 06:04 UTC, 4kangjc commented on async_simple/coro/ConditionVariable.h
> +    ConditionVariableAwaiter<Lock>* _waiters = nullptr;
`_awaiters`是`LIFO` order, `_waiters`是`FIFO`

2022-12-19 06:21 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    ConditionVariableAwaiter<Lock>* _waiters = nullptr;
> _awaiters是LIFO order, _waiters是FIFO

这个区别的话我觉得还是复用下比较好吧，也减少了很多复杂度。而且也不影响 notify_one 的语义，notify_one 应该只要求唤醒任意一个等待的协程就好，对顺序没有要求才对。

2022-12-19 06:22 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    void notifyAll() noexcept;
下面的 ConditionVariable<> 的特化也得加一下这个改动。

2022-12-19 07:52 UTC, RainMark commented on async_simple/coro/ConditionVariable.h
> +    awaitings->_continuation.resume();
看能不能复用下 resumeWaiters

2022-12-20 06:09 UTC, RainMark commented on async_simple/coro/ConditionVariable.h
> +    if (awaitings == nullptr || awaitings == self) {
这里感觉语义有点问题，之前如果先notifyAll后，_awaiters == self, 代表已经通知过了。那么suspend的协程都不会挂起。现在notifyOne理论上先是通知过一次了后，后续只有一个协程suspend时不挂起吧，现在看样子还是都不会挂起。另外_awaiters已经是self了，没必要再exchange为self了吧

2022-12-20 06:10 UTC, ChuanqiXu9 approved these changes
我感觉可以的

2022-12-20 06:10 UTC, RainMark commented on async_simple/coro/test/ConditionVariableTest.cpp
> +TEST_F(ConditionVariableTest, testNotifyOne) {
可以补充个case是，notify先发生于wait之前

2022-12-20 06:13 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    if (awaitings == nullptr || awaitings == self) {
notifyAll 之后再 notifyOne 感觉应该是无意义的吧？这里再设置一下好像是有点多余

2022-12-20 06:15 UTC, RainMark commented on async_simple/coro/ConditionVariable.h
> +    if (awaitings == nullptr || awaitings == self) {
这里说的是notify{All，One}先发生于wait的情况下，原来notifyAll行为是符合预期的，后续wait的都不会挂起。但是notifyOne先发生于wait的话，行为和notifyAll一样了

2022-12-20 06:52 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    awaitings->_continuation.resume();
有道理，可以这么改。resumeWaiters 的实现和类成员其实没有关系，放在类里面有点迷惑了，放出来确实好一些。

2022-12-20 06:56 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    if (awaitings == nullptr || awaitings == self) {
明白你的意思了。那感觉这个问题还不太好处理，需要在 `ConditionVariableAwaiter<void>` 中加入一个新的状态才行。

2022-12-20 07:32 UTC, ChuanqiXu9 requested changes
有挂掉的测试；notifyOne 先于 wait 时的情况可能需要考虑下，感觉可以通过增加一个新的状态来解决

2022-12-20 07:33 UTC, 4kangjc commented
> 有挂掉的测试；notifyOne 先于 wait 时的情况可能需要考虑下，感觉可以通过增加一个新的状态来解决

测试是bazel 6.0的问题，另开一个PR吧

2022-12-20 08:28 UTC, RainMark commented on async_simple/coro/ConditionVariable.h
> +    if (awaitings == nullptr || awaitings == self) {
是的，简单的话可以定一个特殊地址作为notify one过一次的状态，例如self地址取反啥的

2022-12-20 08:40 UTC, 4kangjc commented
我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁
`ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
```cpp
class NullMutex : noncopyable {
public:
    NullMutex() = default;
    ~NullMutex() = default;
    Lazy<> coLock() noexcept { co_return; }
    void lock() noexcept {}
    void unlock() noexcept {}
    Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
    }
};

inline NullMutex nullMutex;

struct Notifier : public ConditionVariable<NullMutex> {
    void wait() { return this->wait(nullMutex); }
};
```

2022-12-20 08:44 UTC, ChuanqiXu9 commented on async_simple/coro/ConditionVariable.h
> +    if (awaitings == nullptr || awaitings == self) {
感觉 `~0x0` 好一些？

2022-12-20 08:49 UTC, ChuanqiXu9 commented
> 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> 
> ```c++
> class NullMutex : noncopyable {
> public:
>     NullMutex() = default;
>     ~NullMutex() = default;
>     Lazy<> coLock() noexcept { co_return; }
>     void lock() noexcept {}
>     void unlock() noexcept {}
>     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
>     }
> };
> 
> inline NullMutex nullMutex;
> 
> struct Notifier : public ConditionVariable<NullMutex> {
>     void wait() { return this->wait(nullMutex); }
> };
> ```

移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要

2022-12-20 08:56 UTC, 4kangjc commented
> > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > ```c++
> > class NullMutex : noncopyable {
> > public:
> >     NullMutex() = default;
> >     ~NullMutex() = default;
> >     Lazy<> coLock() noexcept { co_return; }
> >     void lock() noexcept {}
> >     void unlock() noexcept {}
> >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> >     }
> > };
> > 
> > inline NullMutex nullMutex;
> > 
> > struct Notifier : public ConditionVariable<NullMutex> {
> >     void wait() { return this->wait(nullMutex); }
> > };
> > ```
> 
> 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要

应该没有直接使用`ConditionVariable<void>`吧

2022-12-20 08:59 UTC, RainMark commented
> > > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > > ```c++
> > > class NullMutex : noncopyable {
> > > public:
> > >     NullMutex() = default;
> > >     ~NullMutex() = default;
> > >     Lazy<> coLock() noexcept { co_return; }
> > >     void lock() noexcept {}
> > >     void unlock() noexcept {}
> > >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> > >     }
> > > };
> > > 
> > > inline NullMutex nullMutex;
> > > 
> > > struct Notifier : public ConditionVariable<NullMutex> {
> > >     void wait() { return this->wait(nullMutex); }
> > > };
> > > ```
> > 
> > 
> > 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要
> 
> 应该没有直接使用`ConditionVariable<void>`吧

主意不错，不过Notify有个reset方法，可以反复使用，而普通带lock的cv只能手动更改条件来自行reset后再次使用

2022-12-20 09:08 UTC, 4kangjc commented
> > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > ```c++
> > class NullMutex : noncopyable {
> > public:
> >     NullMutex() = default;
> >     ~NullMutex() = default;
> >     Lazy<> coLock() noexcept { co_return; }
> >     void lock() noexcept {}
> >     void unlock() noexcept {}
> >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> >     }
> > };
> > 
> > inline NullMutex nullMutex;
> > 
> > struct Notifier : public ConditionVariable<NullMutex> {
> >     void wait() { return this->wait(nullMutex); }
> > };
> > ```
> 
> 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要

`Notifier`感觉更像是信号量，而不是条件变量...

2022-12-20 09:11 UTC, 4kangjc commented
> > > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > > ```c++
> > > class NullMutex : noncopyable {
> > > public:
> > >     NullMutex() = default;
> > >     ~NullMutex() = default;
> > >     Lazy<> coLock() noexcept { co_return; }
> > >     void lock() noexcept {}
> > >     void unlock() noexcept {}
> > >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> > >     }
> > > };
> > > 
> > > inline NullMutex nullMutex;
> > > 
> > > struct Notifier : public ConditionVariable<NullMutex> {
> > >     void wait() { return this->wait(nullMutex); }
> > > };
> > > ```
> > 
> > 
> > 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要
> 
> `Notifier`感觉更像是信号量，而不是条件变量...

我们应该实现一个`Semaphore` for `Lazy`

2022-12-20 09:33 UTC, RainMark commented
> > > > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > > > ```c++
> > > > class NullMutex : noncopyable {
> > > > public:
> > > >     NullMutex() = default;
> > > >     ~NullMutex() = default;
> > > >     Lazy<> coLock() noexcept { co_return; }
> > > >     void lock() noexcept {}
> > > >     void unlock() noexcept {}
> > > >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> > > >     }
> > > > };
> > > > 
> > > > inline NullMutex nullMutex;
> > > > 
> > > > struct Notifier : public ConditionVariable<NullMutex> {
> > > >     void wait() { return this->wait(nullMutex); }
> > > > };
> > > > ```
> > > 
> > > 
> > > 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要
> > 
> > 
> > `Notifier`感觉更像是信号量，而不是条件变量...
> 
> 我们应该实现一个`Semaphore` for `Lazy`

哈哈，可能是吧。有cv和mutex了以后都可以直接实现Semaphore等。之前uthread也还差cv，都是await的lazy的cv来用的，有点hack

2022-12-20 09:37 UTC, RainMark commented
> > > > > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > > > > ```c++
> > > > > class NullMutex : noncopyable {
> > > > > public:
> > > > >     NullMutex() = default;
> > > > >     ~NullMutex() = default;
> > > > >     Lazy<> coLock() noexcept { co_return; }
> > > > >     void lock() noexcept {}
> > > > >     void unlock() noexcept {}
> > > > >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> > > > >     }
> > > > > };
> > > > > 
> > > > > inline NullMutex nullMutex;
> > > > > 
> > > > > struct Notifier : public ConditionVariable<NullMutex> {
> > > > >     void wait() { return this->wait(nullMutex); }
> > > > > };
> > > > > ```
> > > > 
> > > > 
> > > > 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要
> > > 
> > > 
> > > `Notifier`感觉更像是信号量，而不是条件变量...
> > 
> > 
> > 我们应该实现一个`Semaphore` for `Lazy`
> 
> 哈哈，可能是吧。有cv和mutex了以后都可以直接实现Semaphore等。之前uthread也还差cv，都是await的lazy的cv来用的，有点hack

实现Notifer另外有一点是在不需要复杂的条件下优化cv的性能，避免用锁

2022-12-20 09:39 UTC, RainMark commented
要不就先加个~0x0 表时notify one了，先合一把代码，然后再讨论其他的优化实现？

2022-12-20 09:40 UTC, ChuanqiXu9 commented
> > > > 我有一个想法，移除`ConditionVaiable`的特化，实现一个空锁 `ConditionVariable`还要实现一个`wait(Lock& lock)`的重载，没有等待条件的那个
> > > > ```c++
> > > > class NullMutex : noncopyable {
> > > > public:
> > > >     NullMutex() = default;
> > > >     ~NullMutex() = default;
> > > >     Lazy<> coLock() noexcept { co_return; }
> > > >     void lock() noexcept {}
> > > >     void unlock() noexcept {}
> > > >     Lazy<std::unique_lock<NullMutex>> coScopedLock() noexcept {
> > > >     }
> > > > };
> > > > 
> > > > inline NullMutex nullMutex;
> > > > 
> > > > struct Notifier : public ConditionVariable<NullMutex> {
> > > >     void wait() { return this->wait(nullMutex); }
> > > > };
> > > > ```
> > > 
> > > 
> > > 移除的话可能会有兼容性问题，而且也没有特别的好处，我觉得没有什么需要
> > 
> > 
> > `Notifier`感觉更像是信号量，而不是条件变量...
> 
> 我们应该实现一个`Semaphore` for `Lazy`

确实可以多加一个 Semaphore，不过感觉加这些东西可能场景先行比较好，即得到什么情况下 Coro Semaphore 会比 Coro CV，Coro Mutex 好等等

2022-12-20 09:41 UTC, ChuanqiXu9 commented
> 要不就先加个~0x0 表示notify one了，先合一把代码，然后再讨论其他的优化实现？

我也觉得

2022-12-20 09:43 UTC, closed without merging

2022-12-20 09:45 UTC, 4kangjc commented
点错了....